// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import Example from "../components/example";
// import Navigation from "../components/navigation";
// import Footer from "../components/footer";
// import LogIn from "./login";
// import Register from "./register";
// import Verification from "./verification";
// import VerificationComplete from "./verification-complete";
// import Verifying from "./verifying";
// import PassphraseWarning from "./passphrase-warning";
// import PassphraseRemember from "./passphrase";
// import PassphraseConfirm from "./passphrase-confirm";
// import AccountCreated from "./account-created";
// import Dashboard from "./dashboard";
// import CoreBusiness from "./core";
// import Link from "next/link";

export default function Home() {
	return null;
	// <div className={styles.container}>
	{
		/* <Head>
        <title>Factiiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Navigation />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <Example />
      </main>

      <Footer /> */
	}

	{
		/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
        </a>
      </footer> */
	}
	// </div>
	// );
}
